name: Actualizar fecha en README

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

on:
  schedule:
    - cron: "0 11 * * *" # Todos los d√≠as a las 6:00 a.m. Lima/Per√∫ (UTC-5)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Actualizar fecha en README
        run: |
          FECHA=$(date +"%d/%m/%Y")
          sed -i "s/^üêà‚Äç‚¨õ Ultima Actu. :.*/üêà‚Äç‚¨õ Ultima Actu. : $FECHA/" README.md

      - name: Configurar Git
        run: |
          git config --local user.name "KitllyCat"
          git config --local user.email "172522452+KitllyCat@users.noreply.github.com"
          git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/KitllyCat/KitllyCat.git

      - name: Commit y push
        run: |
          git add README.md
          git commit -m "Fecha actualizada" || echo "Sin cambios"
          git push
