name: Actualizar fecha diaria

on:
  schedule:
    - cron: "0 11 * * *" # se ejecuta todos los dÃ­as en la maÃ±ana xd (6:00)
  workflow_dispatch: # permite ejecutarlo manualmente desde la pestaÃ±a Actions :3

permissions:
  contents: write

jobs:
  update-date:
    runs-on: ubuntu-latest
    env:
      FILE_PATH: README.md
      PREFIX: "ðŸˆâ€â¬› Ultima Actu. :"
    steps:
      - uses: actions/checkout@v4

      - name: Actualizar fecha (DD/MM/AAAA)
        run: |
          set -e
          fecha=$(date -u "+%d/%m/%Y")
          if grep -q "^$PREFIX" "$FILE_PATH"; then
            sed -i "s|^$PREFIX.*|$PREFIX $fecha|" "$FILE_PATH"
          else
            echo "$PREFIX $fecha" >> "$FILE_PATH"
          fi
          echo "Fecha actualizada a: $PREFIX $fecha"

      - name: Commit y push (si hay cambios)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$FILE_PATH"
          git commit -m "Fecha actualizada nwn" || echo "Sin cambios"
          git push

